baseURL = 'http://117.72.145.20'
languageCode = 'zh-CN'
title = 'dalewang'
theme = "PaperMod"
defaultContentLanguage = "zh"

[params]
  disableSpecial1stPost = true

[menu]
  [[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    name = "书籍"
    url = "/book/"
    weight = 20
  [[menu.main]]
    name = "公告"
    url = "/notice/"
    weight = 30
  [[menu.main]]
    name = "播客"
    url = "/podcast/"
    weight = 40

[permalinks]
  blog   = "/blog/:slug/"
  book   = "/book/:slug/"
  notice = "/notice/:slug/"
  podcast = "/podcast/:slug/"